services:

  # Frontend
  streamlit_app:
    build: .
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    env_file:
      - .env                        # ← so, nicht unter environment
    environment:
      - PYTHONPATH=/workspace
      - OLLAMA_HOST=http://host.docker.internal:11434

    volumes:
      - ./:/workspace

volumes:
  ollama_storage: