services:
  # KI-Modell-Server
  ollama:
    image: ollama/ollama:latest
    container_name: llama_analyse
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama

  # Frontend
  streamlit_app:
    build: .
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    env_file:
      - .env                        # ← so, nicht unter environment
    environment:
      - PYTHONPATH=/workspace
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - ./:/workspace

volumes:
  ollama_storage: